# Generated by Django 5.0.2 on 2024-04-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindeyeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mindeye',
            name='ai_image',
            field=models.ImageField(upload_to='ai_image'),
        ),
    ]
