# Generated by Django 5.0.3 on 2024-04-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindeyeapp', '0003_formdataform'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdataform',
            name='usertype',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
