# Generated by Django 5.0.2 on 2024-04-18 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindeyeapp', '0004_formdataform_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindeye',
            name='uid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mindeyeapp.formdataform'),
        ),
    ]
